// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: radar.proto

package ma.enset.radarservice.grpc.stubs;

public final class Radar {
  private Radar() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface radarInformationsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:radarInformations)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 radarId = 1;</code>
     * @return The radarId.
     */
    long getRadarId();

    /**
     * <code>int64 radarMax = 2;</code>
     * @return The radarMax.
     */
    long getRadarMax();

    /**
     * <code>repeated int64 matricules = 3;</code>
     * @return A list containing the matricules.
     */
    java.util.List<java.lang.Long> getMatriculesList();
    /**
     * <code>repeated int64 matricules = 3;</code>
     * @return The count of matricules.
     */
    int getMatriculesCount();
    /**
     * <code>repeated int64 matricules = 3;</code>
     * @param index The index of the element to return.
     * @return The matricules at the given index.
     */
    long getMatricules(int index);
  }
  /**
   * Protobuf type {@code radarInformations}
   */
  public  static final class radarInformations extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:radarInformations)
      radarInformationsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use radarInformations.newBuilder() to construct.
    private radarInformations(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private radarInformations() {
      matricules_ = emptyLongList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new radarInformations();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private radarInformations(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              radarId_ = input.readInt64();
              break;
            }
            case 16: {

              radarMax_ = input.readInt64();
              break;
            }
            case 24: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                matricules_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              matricules_.addLong(input.readInt64());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                matricules_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                matricules_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          matricules_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.enset.radarservice.grpc.stubs.Radar.internal_static_radarInformations_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.enset.radarservice.grpc.stubs.Radar.internal_static_radarInformations_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.enset.radarservice.grpc.stubs.Radar.radarInformations.class, ma.enset.radarservice.grpc.stubs.Radar.radarInformations.Builder.class);
    }

    public static final int RADARID_FIELD_NUMBER = 1;
    private long radarId_;
    /**
     * <code>int64 radarId = 1;</code>
     * @return The radarId.
     */
    public long getRadarId() {
      return radarId_;
    }

    public static final int RADARMAX_FIELD_NUMBER = 2;
    private long radarMax_;
    /**
     * <code>int64 radarMax = 2;</code>
     * @return The radarMax.
     */
    public long getRadarMax() {
      return radarMax_;
    }

    public static final int MATRICULES_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.LongList matricules_;
    /**
     * <code>repeated int64 matricules = 3;</code>
     * @return A list containing the matricules.
     */
    public java.util.List<java.lang.Long>
        getMatriculesList() {
      return matricules_;
    }
    /**
     * <code>repeated int64 matricules = 3;</code>
     * @return The count of matricules.
     */
    public int getMatriculesCount() {
      return matricules_.size();
    }
    /**
     * <code>repeated int64 matricules = 3;</code>
     * @param index The index of the element to return.
     * @return The matricules at the given index.
     */
    public long getMatricules(int index) {
      return matricules_.getLong(index);
    }
    private int matriculesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (radarId_ != 0L) {
        output.writeInt64(1, radarId_);
      }
      if (radarMax_ != 0L) {
        output.writeInt64(2, radarMax_);
      }
      if (getMatriculesList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(matriculesMemoizedSerializedSize);
      }
      for (int i = 0; i < matricules_.size(); i++) {
        output.writeInt64NoTag(matricules_.getLong(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (radarId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, radarId_);
      }
      if (radarMax_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, radarMax_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < matricules_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(matricules_.getLong(i));
        }
        size += dataSize;
        if (!getMatriculesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        matriculesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.enset.radarservice.grpc.stubs.Radar.radarInformations)) {
        return super.equals(obj);
      }
      ma.enset.radarservice.grpc.stubs.Radar.radarInformations other = (ma.enset.radarservice.grpc.stubs.Radar.radarInformations) obj;

      if (getRadarId()
          != other.getRadarId()) return false;
      if (getRadarMax()
          != other.getRadarMax()) return false;
      if (!getMatriculesList()
          .equals(other.getMatriculesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RADARID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRadarId());
      hash = (37 * hash) + RADARMAX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRadarMax());
      if (getMatriculesCount() > 0) {
        hash = (37 * hash) + MATRICULES_FIELD_NUMBER;
        hash = (53 * hash) + getMatriculesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.enset.radarservice.grpc.stubs.Radar.radarInformations prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code radarInformations}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:radarInformations)
        ma.enset.radarservice.grpc.stubs.Radar.radarInformationsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.enset.radarservice.grpc.stubs.Radar.internal_static_radarInformations_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.enset.radarservice.grpc.stubs.Radar.internal_static_radarInformations_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.enset.radarservice.grpc.stubs.Radar.radarInformations.class, ma.enset.radarservice.grpc.stubs.Radar.radarInformations.Builder.class);
      }

      // Construct using ma.enset.radarservice.grpc.stubs.Radar.radarInformations.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        radarId_ = 0L;

        radarMax_ = 0L;

        matricules_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.enset.radarservice.grpc.stubs.Radar.internal_static_radarInformations_descriptor;
      }

      @java.lang.Override
      public ma.enset.radarservice.grpc.stubs.Radar.radarInformations getDefaultInstanceForType() {
        return ma.enset.radarservice.grpc.stubs.Radar.radarInformations.getDefaultInstance();
      }

      @java.lang.Override
      public ma.enset.radarservice.grpc.stubs.Radar.radarInformations build() {
        ma.enset.radarservice.grpc.stubs.Radar.radarInformations result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.enset.radarservice.grpc.stubs.Radar.radarInformations buildPartial() {
        ma.enset.radarservice.grpc.stubs.Radar.radarInformations result = new ma.enset.radarservice.grpc.stubs.Radar.radarInformations(this);
        int from_bitField0_ = bitField0_;
        result.radarId_ = radarId_;
        result.radarMax_ = radarMax_;
        if (((bitField0_ & 0x00000001) != 0)) {
          matricules_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matricules_ = matricules_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.enset.radarservice.grpc.stubs.Radar.radarInformations) {
          return mergeFrom((ma.enset.radarservice.grpc.stubs.Radar.radarInformations)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.enset.radarservice.grpc.stubs.Radar.radarInformations other) {
        if (other == ma.enset.radarservice.grpc.stubs.Radar.radarInformations.getDefaultInstance()) return this;
        if (other.getRadarId() != 0L) {
          setRadarId(other.getRadarId());
        }
        if (other.getRadarMax() != 0L) {
          setRadarMax(other.getRadarMax());
        }
        if (!other.matricules_.isEmpty()) {
          if (matricules_.isEmpty()) {
            matricules_ = other.matricules_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatriculesIsMutable();
            matricules_.addAll(other.matricules_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.enset.radarservice.grpc.stubs.Radar.radarInformations parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.enset.radarservice.grpc.stubs.Radar.radarInformations) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long radarId_ ;
      /**
       * <code>int64 radarId = 1;</code>
       * @return The radarId.
       */
      public long getRadarId() {
        return radarId_;
      }
      /**
       * <code>int64 radarId = 1;</code>
       * @param value The radarId to set.
       * @return This builder for chaining.
       */
      public Builder setRadarId(long value) {
        
        radarId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 radarId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRadarId() {
        
        radarId_ = 0L;
        onChanged();
        return this;
      }

      private long radarMax_ ;
      /**
       * <code>int64 radarMax = 2;</code>
       * @return The radarMax.
       */
      public long getRadarMax() {
        return radarMax_;
      }
      /**
       * <code>int64 radarMax = 2;</code>
       * @param value The radarMax to set.
       * @return This builder for chaining.
       */
      public Builder setRadarMax(long value) {
        
        radarMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 radarMax = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRadarMax() {
        
        radarMax_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList matricules_ = emptyLongList();
      private void ensureMatriculesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          matricules_ = mutableCopy(matricules_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @return A list containing the matricules.
       */
      public java.util.List<java.lang.Long>
          getMatriculesList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(matricules_) : matricules_;
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @return The count of matricules.
       */
      public int getMatriculesCount() {
        return matricules_.size();
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @param index The index of the element to return.
       * @return The matricules at the given index.
       */
      public long getMatricules(int index) {
        return matricules_.getLong(index);
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @param index The index to set the value at.
       * @param value The matricules to set.
       * @return This builder for chaining.
       */
      public Builder setMatricules(
          int index, long value) {
        ensureMatriculesIsMutable();
        matricules_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @param value The matricules to add.
       * @return This builder for chaining.
       */
      public Builder addMatricules(long value) {
        ensureMatriculesIsMutable();
        matricules_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @param values The matricules to add.
       * @return This builder for chaining.
       */
      public Builder addAllMatricules(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMatriculesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matricules_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 matricules = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMatricules() {
        matricules_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:radarInformations)
    }

    // @@protoc_insertion_point(class_scope:radarInformations)
    private static final ma.enset.radarservice.grpc.stubs.Radar.radarInformations DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.enset.radarservice.grpc.stubs.Radar.radarInformations();
    }

    public static ma.enset.radarservice.grpc.stubs.Radar.radarInformations getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<radarInformations>
        PARSER = new com.google.protobuf.AbstractParser<radarInformations>() {
      @java.lang.Override
      public radarInformations parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new radarInformations(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<radarInformations> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<radarInformations> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.enset.radarservice.grpc.stubs.Radar.radarInformations getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface infractionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:infraction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 radarNumber = 1;</code>
     * @return The radarNumber.
     */
    long getRadarNumber();

    /**
     * <code>int64 vehiculeMatricule = 2;</code>
     * @return The vehiculeMatricule.
     */
    long getVehiculeMatricule();

    /**
     * <code>int64 vehiculeSpeed = 3;</code>
     * @return The vehiculeSpeed.
     */
    long getVehiculeSpeed();

    /**
     * <code>int64 maxSpeedRadar = 4;</code>
     * @return The maxSpeedRadar.
     */
    long getMaxSpeedRadar();
  }
  /**
   * Protobuf type {@code infraction}
   */
  public  static final class infraction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:infraction)
      infractionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use infraction.newBuilder() to construct.
    private infraction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private infraction() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new infraction();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private infraction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              radarNumber_ = input.readInt64();
              break;
            }
            case 16: {

              vehiculeMatricule_ = input.readInt64();
              break;
            }
            case 24: {

              vehiculeSpeed_ = input.readInt64();
              break;
            }
            case 32: {

              maxSpeedRadar_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.enset.radarservice.grpc.stubs.Radar.internal_static_infraction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.enset.radarservice.grpc.stubs.Radar.internal_static_infraction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.enset.radarservice.grpc.stubs.Radar.infraction.class, ma.enset.radarservice.grpc.stubs.Radar.infraction.Builder.class);
    }

    public static final int RADARNUMBER_FIELD_NUMBER = 1;
    private long radarNumber_;
    /**
     * <code>int64 radarNumber = 1;</code>
     * @return The radarNumber.
     */
    public long getRadarNumber() {
      return radarNumber_;
    }

    public static final int VEHICULEMATRICULE_FIELD_NUMBER = 2;
    private long vehiculeMatricule_;
    /**
     * <code>int64 vehiculeMatricule = 2;</code>
     * @return The vehiculeMatricule.
     */
    public long getVehiculeMatricule() {
      return vehiculeMatricule_;
    }

    public static final int VEHICULESPEED_FIELD_NUMBER = 3;
    private long vehiculeSpeed_;
    /**
     * <code>int64 vehiculeSpeed = 3;</code>
     * @return The vehiculeSpeed.
     */
    public long getVehiculeSpeed() {
      return vehiculeSpeed_;
    }

    public static final int MAXSPEEDRADAR_FIELD_NUMBER = 4;
    private long maxSpeedRadar_;
    /**
     * <code>int64 maxSpeedRadar = 4;</code>
     * @return The maxSpeedRadar.
     */
    public long getMaxSpeedRadar() {
      return maxSpeedRadar_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (radarNumber_ != 0L) {
        output.writeInt64(1, radarNumber_);
      }
      if (vehiculeMatricule_ != 0L) {
        output.writeInt64(2, vehiculeMatricule_);
      }
      if (vehiculeSpeed_ != 0L) {
        output.writeInt64(3, vehiculeSpeed_);
      }
      if (maxSpeedRadar_ != 0L) {
        output.writeInt64(4, maxSpeedRadar_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (radarNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, radarNumber_);
      }
      if (vehiculeMatricule_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, vehiculeMatricule_);
      }
      if (vehiculeSpeed_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, vehiculeSpeed_);
      }
      if (maxSpeedRadar_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, maxSpeedRadar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ma.enset.radarservice.grpc.stubs.Radar.infraction)) {
        return super.equals(obj);
      }
      ma.enset.radarservice.grpc.stubs.Radar.infraction other = (ma.enset.radarservice.grpc.stubs.Radar.infraction) obj;

      if (getRadarNumber()
          != other.getRadarNumber()) return false;
      if (getVehiculeMatricule()
          != other.getVehiculeMatricule()) return false;
      if (getVehiculeSpeed()
          != other.getVehiculeSpeed()) return false;
      if (getMaxSpeedRadar()
          != other.getMaxSpeedRadar()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RADARNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRadarNumber());
      hash = (37 * hash) + VEHICULEMATRICULE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVehiculeMatricule());
      hash = (37 * hash) + VEHICULESPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVehiculeSpeed());
      hash = (37 * hash) + MAXSPEEDRADAR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMaxSpeedRadar());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ma.enset.radarservice.grpc.stubs.Radar.infraction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ma.enset.radarservice.grpc.stubs.Radar.infraction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code infraction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:infraction)
        ma.enset.radarservice.grpc.stubs.Radar.infractionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ma.enset.radarservice.grpc.stubs.Radar.internal_static_infraction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ma.enset.radarservice.grpc.stubs.Radar.internal_static_infraction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ma.enset.radarservice.grpc.stubs.Radar.infraction.class, ma.enset.radarservice.grpc.stubs.Radar.infraction.Builder.class);
      }

      // Construct using ma.enset.radarservice.grpc.stubs.Radar.infraction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        radarNumber_ = 0L;

        vehiculeMatricule_ = 0L;

        vehiculeSpeed_ = 0L;

        maxSpeedRadar_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ma.enset.radarservice.grpc.stubs.Radar.internal_static_infraction_descriptor;
      }

      @java.lang.Override
      public ma.enset.radarservice.grpc.stubs.Radar.infraction getDefaultInstanceForType() {
        return ma.enset.radarservice.grpc.stubs.Radar.infraction.getDefaultInstance();
      }

      @java.lang.Override
      public ma.enset.radarservice.grpc.stubs.Radar.infraction build() {
        ma.enset.radarservice.grpc.stubs.Radar.infraction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ma.enset.radarservice.grpc.stubs.Radar.infraction buildPartial() {
        ma.enset.radarservice.grpc.stubs.Radar.infraction result = new ma.enset.radarservice.grpc.stubs.Radar.infraction(this);
        result.radarNumber_ = radarNumber_;
        result.vehiculeMatricule_ = vehiculeMatricule_;
        result.vehiculeSpeed_ = vehiculeSpeed_;
        result.maxSpeedRadar_ = maxSpeedRadar_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ma.enset.radarservice.grpc.stubs.Radar.infraction) {
          return mergeFrom((ma.enset.radarservice.grpc.stubs.Radar.infraction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ma.enset.radarservice.grpc.stubs.Radar.infraction other) {
        if (other == ma.enset.radarservice.grpc.stubs.Radar.infraction.getDefaultInstance()) return this;
        if (other.getRadarNumber() != 0L) {
          setRadarNumber(other.getRadarNumber());
        }
        if (other.getVehiculeMatricule() != 0L) {
          setVehiculeMatricule(other.getVehiculeMatricule());
        }
        if (other.getVehiculeSpeed() != 0L) {
          setVehiculeSpeed(other.getVehiculeSpeed());
        }
        if (other.getMaxSpeedRadar() != 0L) {
          setMaxSpeedRadar(other.getMaxSpeedRadar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ma.enset.radarservice.grpc.stubs.Radar.infraction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ma.enset.radarservice.grpc.stubs.Radar.infraction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long radarNumber_ ;
      /**
       * <code>int64 radarNumber = 1;</code>
       * @return The radarNumber.
       */
      public long getRadarNumber() {
        return radarNumber_;
      }
      /**
       * <code>int64 radarNumber = 1;</code>
       * @param value The radarNumber to set.
       * @return This builder for chaining.
       */
      public Builder setRadarNumber(long value) {
        
        radarNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 radarNumber = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRadarNumber() {
        
        radarNumber_ = 0L;
        onChanged();
        return this;
      }

      private long vehiculeMatricule_ ;
      /**
       * <code>int64 vehiculeMatricule = 2;</code>
       * @return The vehiculeMatricule.
       */
      public long getVehiculeMatricule() {
        return vehiculeMatricule_;
      }
      /**
       * <code>int64 vehiculeMatricule = 2;</code>
       * @param value The vehiculeMatricule to set.
       * @return This builder for chaining.
       */
      public Builder setVehiculeMatricule(long value) {
        
        vehiculeMatricule_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 vehiculeMatricule = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehiculeMatricule() {
        
        vehiculeMatricule_ = 0L;
        onChanged();
        return this;
      }

      private long vehiculeSpeed_ ;
      /**
       * <code>int64 vehiculeSpeed = 3;</code>
       * @return The vehiculeSpeed.
       */
      public long getVehiculeSpeed() {
        return vehiculeSpeed_;
      }
      /**
       * <code>int64 vehiculeSpeed = 3;</code>
       * @param value The vehiculeSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setVehiculeSpeed(long value) {
        
        vehiculeSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 vehiculeSpeed = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehiculeSpeed() {
        
        vehiculeSpeed_ = 0L;
        onChanged();
        return this;
      }

      private long maxSpeedRadar_ ;
      /**
       * <code>int64 maxSpeedRadar = 4;</code>
       * @return The maxSpeedRadar.
       */
      public long getMaxSpeedRadar() {
        return maxSpeedRadar_;
      }
      /**
       * <code>int64 maxSpeedRadar = 4;</code>
       * @param value The maxSpeedRadar to set.
       * @return This builder for chaining.
       */
      public Builder setMaxSpeedRadar(long value) {
        
        maxSpeedRadar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 maxSpeedRadar = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxSpeedRadar() {
        
        maxSpeedRadar_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:infraction)
    }

    // @@protoc_insertion_point(class_scope:infraction)
    private static final ma.enset.radarservice.grpc.stubs.Radar.infraction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ma.enset.radarservice.grpc.stubs.Radar.infraction();
    }

    public static ma.enset.radarservice.grpc.stubs.Radar.infraction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<infraction>
        PARSER = new com.google.protobuf.AbstractParser<infraction>() {
      @java.lang.Override
      public infraction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new infraction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<infraction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<infraction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ma.enset.radarservice.grpc.stubs.Radar.infraction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_radarInformations_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_radarInformations_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_infraction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_infraction_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013radar.proto\"J\n\021radarInformations\022\017\n\007ra" +
      "darId\030\001 \001(\003\022\020\n\010radarMax\030\002 \001(\003\022\022\n\nmatricu" +
      "les\030\003 \003(\003\"j\n\ninfraction\022\023\n\013radarNumber\030\001" +
      " \001(\003\022\031\n\021vehiculeMatricule\030\002 \001(\003\022\025\n\rvehic" +
      "uleSpeed\030\003 \001(\003\022\025\n\rmaxSpeedRadar\030\004 \001(\0032@\n" +
      "\013radarDevice\0221\n\014getConnected\022\022.radarInfo" +
      "rmations\032\013.infraction0\001B\"\n ma.enset.rada" +
      "rservice.grpc.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_radarInformations_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_radarInformations_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_radarInformations_descriptor,
        new java.lang.String[] { "RadarId", "RadarMax", "Matricules", });
    internal_static_infraction_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_infraction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_infraction_descriptor,
        new java.lang.String[] { "RadarNumber", "VehiculeMatricule", "VehiculeSpeed", "MaxSpeedRadar", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
