spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8081/
          predicates :
            - Path= /vehicules/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path= /radars/**
        - id: r3
          uri: http://localhost:8083/
          predicates:
            - Path= /infractions/**
    discovery:
      enabled: false
server:
  port: 8888

